### ISSUE TITLE
Deform along curve

### ISSUE THREAD

**Issue by haracas** [jobweek/CurveArray#9]
Is there a way to deform the curve objects along the curve so that a repeating object appears to be joined as a chain?

![Screenshot 2023-07-20 at 12 37 07 AM](https://github.com/jobweek/CurveArray/assets/118073229/1e3797a4-f628-4ce9-abe6-557460a6f80a)

**Comment by jobweek** [comment]
Curve Array was designed not to deform the array objects) But, you can create the array you want on a straight line using Curve Array (step 1), then merge the objects into one and use Blender's built-in Curve modifier to deform the objects along the curve you want (step 2).

Step 1
![step 1](https://github.com/jobweek/CurveArray/assets/57871127/32499ba8-ca8f-4bde-88fd-9dd871afceb8)

Step 2
![step 2](https://github.com/jobweek/CurveArray/assets/57871127/f53db5f9-7247-4b30-808a-482a4fd6292e)
